### ISSUE TITLE
withdraw/SRS & deposit/RSR

### ISSUE THREAD

**Issue by aifeelit** [MimbleWimble-Grin/grin-testnet-deposit-withdraw#1]
We need to withdraw and deposit with SRS method.
not RSR
it's really complicated for users also for developers those who are very familiar with it.

**Comment by ben07ab** [comment]
it is not supported by grin-wallet invented so far

**Comment by aifeelit** [comment]
oh, man
we can't do that? CAN!!!
send receipt with slate pack

**Comment by wp-dream111** [comment]
hi ben?!

**Comment by wp-dream111** [comment]
use your head! not crash into the wall... lol

**Comment by wp-dream111** [comment]
Log in to your account and click Holdings in the upper right of the site.
Search for the Grin wallet.
Click Withdrawals under Holdings to bring up the withdrawal page.

**Comment by ben07ab** [comment]
what? crash? ang?

**Comment by ben07ab** [comment]
you are a genius
